name: Coveralls

on:
  workflow_run:
    workflows: [Linux]
    types:
      - completed

jobs:
  finish:
    runs-on: ubuntu-latest
    env:
      NODE_COVERALLS_DEBUG: 1

    steps:
      - name: Coveralls Finished
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel-finished: true
        env:
          COVERALLS_SERVICE_JOB_ID: glog-${{steps.date.outputs.date}}-${{github.run_number}}
